# Generated by Django 5.2.5 on 2025-08-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('moment', models.CharField(choices=[('1', 'SERVICO DE CANTICO'), ('2', 'MENSGAEM MUSICAL'), ('3', 'OFERTORIO'), ('4', 'ARCA DE ORACAO'), ('5', 'DISPERSAO DAS CLASSES'), ('6', 'DESPEDIDA')], default='1', max_length=200)),
                ('sing_date', models.DateTimeField()),
            ],
        ),
    ]
