# Generated by Django 5.2.5 on 2025-08-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moments',
            name='description',
        ),
    ]
