# Generated by Django 5.2.5 on 2025-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_music_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='moment',
            field=models.CharField(max_length=200),
        ),
    ]
