# Generated by Django 5.2.5 on 2025-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_music_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='moment',
            field=models.CharField(choices=[('1', 'SERVICO DE CANTICO'), ('2', 'MENSAGEM MUSICAL'), ('3', 'OFERTORIO'), ('4', 'ARCA DE ORACAO'), ('5', 'DISPERSAO DAS CLASSES'), ('6', 'DESPEDIDA')], max_length=200),
        ),
    ]
